port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: AKUN1
    server: fr1.test3.net
    port: 443
    type: trojan
    password: 4a452c00-ce5d-11ef-a7b8-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: AKUN2
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 4a452c00-ce5d-11ef-a7b8-1239d0255272
    skip-cert-verify: true
    sni: fr1.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: fr1.test3.net
    udp: true
  - name: AKUN3
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 4a452c00-ce5d-11ef-a7b8-1239d0255272
    skip-cert-verify: true
    sni: fr1.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: fr1.test3.net
    udp: true
  - name: AKUN4
    server: sg4.6n6.net
    port: 443
    type: trojan
    password: 5de80480-ce5d-11ef-b2c4-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: AKUN5
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 5de80480-ce5d-11ef-b2c4-1239d0255272
    skip-cert-verify: true
    sni: sg4.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg4.6n6.net
    udp: true
  - name: AKUN6
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 5de80480-ce5d-11ef-b2c4-1239d0255272
    skip-cert-verify: true
    sni: sg4.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg4.6n6.net
    udp: true
  - name: AKUN7
    server: uk1.test3.net
    port: 443
    type: trojan
    password: 6fa57bc0-ce5d-11ef-a47f-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: AKUN8
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 6fa57bc0-ce5d-11ef-a47f-1239d0255272
    skip-cert-verify: true
    sni: uk1.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: uk1.test3.net
    udp: true
  - name: AKUN9
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 6fa57bc0-ce5d-11ef-a47f-1239d0255272
    skip-cert-verify: true
    sni: uk1.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: uk1.test3.net
    udp: true
  - name: AKUN10
    server: sg1.6n6.net
    port: 443
    type: trojan
    password: 9d7905a0-ce5d-11ef-b05a-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: AKUN11
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 9d7905a0-ce5d-11ef-b05a-1239d0255272
    skip-cert-verify: true
    sni: sg1.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg1.6n6.net
    udp: true
  - name: AKUN12
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 9d7905a0-ce5d-11ef-b05a-1239d0255272
    skip-cert-verify: true
    sni: sg1.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg1.6n6.net
    udp: true
  - name: AKUN13
    server: usa.test3.net
    port: 443
    type: trojan
    password: b37c9d70-ce5d-11ef-b672-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: AKUN14
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: b37c9d70-ce5d-11ef-b672-1239d0255272
    skip-cert-verify: true
    sni: usa.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: usa.test3.net
    udp: true
  - name: AKUN15
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: b37c9d70-ce5d-11ef-b672-1239d0255272
    skip-cert-verify: true
    sni: usa.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: usa.test3.net
    udp: true
  - name: AKUN16
    server: sg3.6n6.net
    port: 443
    type: trojan
    password: ca7c0c70-ce5d-11ef-8a15-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: AKUN17
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: ca7c0c70-ce5d-11ef-8a15-1239d0255272
    skip-cert-verify: true
    sni: sg3.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg3.6n6.net
    udp: true
  - name: AKUN18
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: ca7c0c70-ce5d-11ef-8a15-1239d0255272
    skip-cert-verify: true
    sni: sg3.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg3.6n6.net
    udp: true
  - name: AKUN19
    server: sg2.6n6.net
    port: 443
    type: trojan
    password: 4482eff0-ce5e-11ef-8ea5-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: AKUN20
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 4482eff0-ce5e-11ef-8ea5-1239d0255272
    skip-cert-verify: true
    sni: sg2.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg2.6n6.net
    udp: true
  - name: AKUN21
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 4482eff0-ce5e-11ef-8ea5-1239d0255272
    skip-cert-verify: true
    sni: sg2.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg2.6n6.net
    udp: true
  - name: AKUN22
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: jagoanssh-WEDWWEFR
    skip-cert-verify: true
    sni: id1go.ipservers.xyz
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: id1go.ipservers.xyz
    udp: true
  - name: AKUN23
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: jagoanssh-QWEDQWE
    skip-cert-verify: true
    sni: id2go.ipservers.xyz
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: id2go.ipservers.xyz
    udp: true
  - name: AKUN24
    server: quiz.int.vidio.com
    port: 443
    type: vmess
    uuid: ffa972f7-8670-4888-8ae4-e98ed2752e24
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id1-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id1-ray.ipservers.xyz
    udp: true
  - name: AKUN25
    server: quiz.int.vidio.com
    port: 80
    type: vmess
    uuid: ffa972f7-8670-4888-8ae4-e98ed2752e24
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id1-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id1-ray.ipservers.xyz
    udp: true
  - name: AKUN26
    server: quiz.int.vidio.com
    port: 443
    type: vmess
    uuid: 396415b0-6f7d-4df3-9d50-1a3ff9115b1a
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id2-ray.ipservers.xyz
    udp: true
  - name: AKUN27
    server: quiz.int.vidio.com
    port: 80
    type: vmess
    uuid: 396415b0-6f7d-4df3-9d50-1a3ff9115b1a
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id2-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id2-ray.ipservers.xyz
    udp: true
  - name: AKUN28
    server: quiz.int.vidio.com
    port: 443
    type: vless
    uuid: 9cf9a9b0-2e2e-45bd-ac6f-5eaa44e30cfe
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id1vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /jagoanssh
      headers:
        Host: id1vless.ipservers.xyz
    udp: true
  - name: AKUN29
    server: quiz.int.vidio.com
    port: 443
    type: vless
    uuid: aae98731-898a-4cd3-8c7f-d09af2387d63
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /jagoanssh
      headers:
        Host: id2vless.ipservers.xyz
    udp: true
  - name: AKUN30
    server: quiz.int.vidio.com
    port: 443
    type: vmess
    uuid: e200e6c5-f946-4501-9ae9-c04a1bd65dc9
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id1-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id1-ray.ipservers.xyz
    udp: true
  - name: AKUN31
    server: quiz.int.vidio.com
    port: 80
    type: vmess
    uuid: e200e6c5-f946-4501-9ae9-c04a1bd65dc9
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id1-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id1-ray.ipservers.xyz
    udp: true
  - name: AKUN32
    server: quiz.int.vidio.com
    port: 443
    type: vmess
    uuid: 4652890a-0ec8-455b-be67-e196ad8d5e86
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id2-ray.ipservers.xyz
    udp: true
  - name: AKUN33
    server: quiz.int.vidio.com
    port: 80
    type: vmess
    uuid: 4652890a-0ec8-455b-be67-e196ad8d5e86
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id2-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id2-ray.ipservers.xyz
    udp: true
  - name: AKUN34
    server: quiz.int.vidio.com
    port: 443
    type: vless
    uuid: 07747c81-c480-4768-ac90-fccf76ad2864
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id1vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /jagoanssh
      headers:
        Host: id1vless.ipservers.xyz
    udp: true
  - name: AKUN35
    server: quiz.int.vidio.com
    port: 443
    type: vless
    uuid: 4974d864-6e59-485e-a024-22c1fd3c9658
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /jagoanssh
      headers:
        Host: id2vless.ipservers.xyz
    udp: true
proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN22
      - AKUN23
      - AKUN24
      - AKUN25
      - AKUN26
      - AKUN27
      - AKUN28
      - AKUN29
      - AKUN30
      - AKUN31
      - AKUN32
      - AKUN33
      - AKUN34
      - AKUN35
  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - AKUN1
      - AKUN2
      - AKUN3
      - AKUN4
      - AKUN5
      - AKUN6
      - AKUN7
      - AKUN8
      - AKUN9
      - AKUN10
      - AKUN11
      - AKUN12
      - AKUN13
      - AKUN14
      - AKUN15
      - AKUN16
      - AKUN17
      - AKUN18
      - AKUN19
      - AKUN20
      - AKUN21
      - AKUN22
      - AKUN23
      - AKUN24
      - AKUN25
      - AKUN26
      - AKUN27
      - AKUN28
      - AKUN29
      - AKUN30
      - AKUN31
      - AKUN32
      - AKUN33
      - AKUN34
      - AKUN35
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

  - name: GITHUB
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
     - MIX-X
     - DIRECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Github,GITHUB
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Github:
    type: file
    behavior: classical
    path: ./github.yaml 
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  
