port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: "[Trojan] fr1.test3.net"
    server: fr1.test3.net
    port: 443
    type: trojan
    password: 4a452c00-ce5d-11ef-a7b8-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: "[Trojan] quiz.int.vidio.com"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 4a452c00-ce5d-11ef-a7b8-1239d0255272
    skip-cert-verify: true
    sni: fr1.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: fr1.test3.net
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 2"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 4a452c00-ce5d-11ef-a7b8-1239d0255272
    skip-cert-verify: true
    sni: fr1.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: fr1.test3.net
    udp: true
  - name: "[Trojan] 🇸🇬 sg4.6n6.net"
    server: sg4.6n6.net
    port: 443
    type: trojan
    password: 5de80480-ce5d-11ef-b2c4-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 3"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 5de80480-ce5d-11ef-b2c4-1239d0255272
    skip-cert-verify: true
    sni: sg4.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg4.6n6.net
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 4"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 5de80480-ce5d-11ef-b2c4-1239d0255272
    skip-cert-verify: true
    sni: sg4.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg4.6n6.net
    udp: true
  - name: "[Trojan] 🇬🇧 uk1.test3.net"
    server: uk1.test3.net
    port: 443
    type: trojan
    password: 6fa57bc0-ce5d-11ef-a47f-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 5"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 6fa57bc0-ce5d-11ef-a47f-1239d0255272
    skip-cert-verify: true
    sni: uk1.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: uk1.test3.net
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 6"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 6fa57bc0-ce5d-11ef-a47f-1239d0255272
    skip-cert-verify: true
    sni: uk1.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: uk1.test3.net
    udp: true
  - name: "[Trojan] 🇸🇬 sg1.6n6.net"
    server: sg1.6n6.net
    port: 443
    type: trojan
    password: 9d7905a0-ce5d-11ef-b05a-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 7"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 9d7905a0-ce5d-11ef-b05a-1239d0255272
    skip-cert-verify: true
    sni: sg1.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg1.6n6.net
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 8"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 9d7905a0-ce5d-11ef-b05a-1239d0255272
    skip-cert-verify: true
    sni: sg1.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg1.6n6.net
    udp: true
  - name: "[Trojan] 🇺🇸 usa.test3.net"
    server: usa.test3.net
    port: 443
    type: trojan
    password: b37c9d70-ce5d-11ef-b672-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 9"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: b37c9d70-ce5d-11ef-b672-1239d0255272
    skip-cert-verify: true
    sni: usa.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: usa.test3.net
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 10"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: b37c9d70-ce5d-11ef-b672-1239d0255272
    skip-cert-verify: true
    sni: usa.test3.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: usa.test3.net
    udp: true
  - name: "[Trojan] 🇸🇬 sg3.6n6.net"
    server: sg3.6n6.net
    port: 443
    type: trojan
    password: ca7c0c70-ce5d-11ef-8a15-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 11"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: ca7c0c70-ce5d-11ef-8a15-1239d0255272
    skip-cert-verify: true
    sni: sg3.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg3.6n6.net
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 12"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: ca7c0c70-ce5d-11ef-8a15-1239d0255272
    skip-cert-verify: true
    sni: sg3.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg3.6n6.net
    udp: true
  - name: "[Trojan] 🇸🇬 sg2.6n6.net"
    server: sg2.6n6.net
    port: 443
    type: trojan
    password: 4482eff0-ce5e-11ef-8ea5-1239d0255272
    skip-cert-verify: true
    sni: quiz.int.vidio.com
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 13"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 4482eff0-ce5e-11ef-8ea5-1239d0255272
    skip-cert-verify: true
    sni: sg2.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg2.6n6.net
    udp: true
  - name: "[Trojan] quiz.int.vidio.com 14"
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: 4482eff0-ce5e-11ef-8ea5-1239d0255272
    skip-cert-verify: true
    sni: sg2.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg2.6n6.net
    udp: true



  - name: id1go.ipservers.xyz
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: jagoanssh-WEDWWEFR
    skip-cert-verify: true
    sni: id1go.ipservers.xyz
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: id1go.ipservers.xyz
    udp: true
  - name: id2go.ipservers.xyz
    server: quiz.int.vidio.com
    port: 443
    type: trojan
    password: jagoanssh-QWEDQWE
    skip-cert-verify: true
    sni: id2go.ipservers.xyz
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: id2go.ipservers.xyz
    udp: true
  - name: jagoanssh-werwrt34
    server: quiz.int.vidio.com
    port: 443
    type: vmess
    uuid: ffa972f7-8670-4888-8ae4-e98ed2752e24
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id1-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id1-ray.ipservers.xyz
    udp: true
  - name: jagoanssh-werwrt34 2
    server: quiz.int.vidio.com
    port: 80
    type: vmess
    uuid: ffa972f7-8670-4888-8ae4-e98ed2752e24
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id1-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id1-ray.ipservers.xyz
    udp: true
  - name: jagoanssh-wqergwe
    server: quiz.int.vidio.com
    port: 443
    type: vmess
    uuid: 396415b0-6f7d-4df3-9d50-1a3ff9115b1a
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id2-ray.ipservers.xyz
    udp: true
  - name: jagoanssh-wqergwe 2
    server: quiz.int.vidio.com
    port: 80
    type: vmess
    uuid: 396415b0-6f7d-4df3-9d50-1a3ff9115b1a
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id2-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id2-ray.ipservers.xyz
    udp: true
  - name: jagoanssh-sdfsdfsd
    server: quiz.int.vidio.com
    port: 443
    type: vless
    uuid: 9cf9a9b0-2e2e-45bd-ac6f-5eaa44e30cfe
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id1vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /jagoanssh
      headers:
        Host: id1vless.ipservers.xyz
    udp: true
  - name: jagoanssh-ytyrtrge
    server: quiz.int.vidio.com
    port: 443
    type: vless
    uuid: aae98731-898a-4cd3-8c7f-d09af2387d63
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /jagoanssh
      headers:
        Host: id2vless.ipservers.xyz
    udp: true



proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - id1go.ipservers.xyz
      - id2go.ipservers.xyz
      - jagoanssh-werwrt34
      - jagoanssh-werwrt34 2
      - jagoanssh-wqergwe
      - jagoanssh-wqergwe 2
      - jagoanssh-sdfsdfsd
      - jagoanssh-ytyrtrge

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "[Trojan] fr1.test3.net"
      - "[Trojan] quiz.int.vidio.com"
      - "[Trojan] quiz.int.vidio.com 2"
      - "[Trojan] 🇸🇬 sg4.6n6.net"
      - "[Trojan] quiz.int.vidio.com 3"
      - "[Trojan] quiz.int.vidio.com 4"
      - "[Trojan] 🇬🇧 uk1.test3.net"
      - "[Trojan] quiz.int.vidio.com 5"
      - "[Trojan] quiz.int.vidio.com 6"
      - "[Trojan] 🇸🇬 sg1.6n6.net"
      - "[Trojan] quiz.int.vidio.com 7"
      - "[Trojan] quiz.int.vidio.com 8"
      - "[Trojan] 🇺🇸 usa.test3.net"
      - "[Trojan] quiz.int.vidio.com 9"
      - "[Trojan] quiz.int.vidio.com 10"
      - "[Trojan] 🇸🇬 sg3.6n6.net"
      - "[Trojan] quiz.int.vidio.com 11"
      - "[Trojan] quiz.int.vidio.com 12"
      - "[Trojan] 🇸🇬 sg2.6n6.net"
      - "[Trojan] quiz.int.vidio.com 13"
      - "[Trojan] quiz.int.vidio.com 14"

  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  